Manualis atvizsgalas
BME-MIT-IET/iet-hf-2024-foaf-strukturalhatatlan_kenyer pull request #8
Opened 2024-05-21 16:11 UTC by s-virag

Elvégeztük az osztályokon a manuális átvizsgálást

2024-05-21 17:16 UTC, 4321ba requested changes
Mindjárt kipróbálom a Simi által csinált CI-vel h lefordul-e, ha nem akkor nem illik mergelni :SS

2024-05-21 17:16 UTC, 4321ba commented on drukmakor/src/main/java/drukmakor/Cistern.java
> +>>>>>>> Stashed changes
Emiatt szerintem nem kéne lefordulnia

2024-05-21 17:16 UTC, 4321ba commented on drukmakor/src/main/java/drukmakor/Cistern.java
> +>>>>>>> Stashed changes
meg ez, ezek ilyen különbség cuccnak tűnnek, hogy 2 közül valamelyiket elfogadjuk, de a véglegesben nem kéne mergelni sztem

2024-05-21 17:16 UTC, 4321ba commented on drukmakor/src/main/java/drukmakor/Pipe.java
> -			//50 PONT A GRIFFENDÉLNEK
Ez Simi volt xd

2024-05-21 17:16 UTC, 4321ba commented on drukmakor/src/main/java/drukmakor/Pipe.java
> -		isOccupied = false; //temporary, hogy  a többi működjön
sry a Hunglishert, ez valszeg én voltam bár nem tuti xd

2024-05-21 17:16 UTC, 4321ba commented on drukmakor/.vs/VSWorkspaceState.json
nem vagyok meggyőzve h a vs különböző fájljait szívesen fogadjuk, de nem is árt vszeg xd

2024-05-21 17:19 UTC, 4321ba commented
Ehh igen, a Cistern.java-ba került diff izék vagy mik miatt nem tud fordulni, azt még szedd ki pls :'DD

2024-05-22 09:45 UTC, 4321ba approved these changes
Szupi!

2024-05-22 09:45 UTC, merged

2024-05-22 09:46 UTC, 4321ba commented
Inkább mégis meghagyom a branchet is

2024-05-22 13:06 UTC, s-virag commented
partly fixes #2